- BTAS.js
- README.md
Reverts Ripper-S/BTAS#9
Code style fix
> Revert "Dev"

- BTAS.js
- README.md
add jira search log source domain field
> add Jira search

- BTAS.js
> Revert "fix CB undefined bug; add CB cef log parse(jetco)"

- BTAS.js
1. 增加对Jetco客户CEF Log的解析，对参数中包含空格的情况做了处理，解析为JSON格式方便读取
2. 对Jetco dev类型的工单，比如server error，会将服务器名称添加进dsecription
> add Jetco log parse

- BTAS.js
1. 根据Ticket Auto Escalate字段，把所有自动升级的工单都添加提醒
2. 把一些经常使用的常量提出来作为全局变量，比如labels，logsource
> add auto escalate ticket notify

- BTAS.js
- notify.json
1. 将配置文件更新地址放到腾讯云上，缓存时间设置为12h
2. 判定自动升级的工单增加Status为waitting for customer的条件
> update notify file address

- BTAS.js
修复了sangfor平台无法生成description的bug
> fix sangfor decoder bug

- BTAS.js
1. 在生成Description时增加对command line长度作为判断依据，将command line最长的字段找出来。比如actor_process_command_line最长则表示信息量最多，避免输出Explorer.exe之类的系统文件或进程，输出真正产生告警的进程信息。然后将actor file name\path\hash等作为要输出的数据。如果command长度相同则输出字段最完整的；如果字段都一样完整，则按照action->actor->causally->os的调用链顺序输出
2. 删除了if not please remove it and perform a full scan.语句
> update cortex description

- BTAS.js
针对htsc一些扫描类告警，Description只提取不同tag里最近的一次告警
> optimize htsc desc

- BTAS.js
> optimize checkOrg function

- BTAS.js
> fix description resolve to emoji

- BTAS.js
1. 将收集的Keywords文件放在云端，通过网络获取更新
2. 使用setTimeout()替换setInterval()，提高程序运行效率
> update keywords check

- BTAS.js
> add custom reply

- BTAS.js
> add sophos jump

- BTAS.js
increase check function timeout
> Optimize notify function

- BTAS.js
> optimize windows event decoder generate desc

- BTAS.js
Jira搜索时默认添加host，只搜索同一台主机上的相同告警
> add default host field search

- BTAS.js
> add azure decoder

- BTAS.js
> updated the flow of AzureGraphAlertHandler function (conditional access policy updated)

- BTAS.js
With title matching tickets, decoder name (azuregraphapi-json) does not process tickets for that title
> add summary(successful azure/o365 login from malware-ip) handler

- BTAS.js
…，fortigate-firewall-v5) description
> Added time information to the (paloalto-firewall，windows_eventchannel，fortigate-firewall-v5) description

- BTAS.js
…time zero zone highlighting in the description
> Added time information to the (m365-defender-json) description,Added time zero zone highlighting in the description

- BTAS.js
…phAPI-json,sophos) description
> Added time information to the (impervainc_cef,aws-cloudtrail,AzureGraphAPI-json,sophos) description 

- BTAS.js
> add aws-guardduty handler and Modified the style of the number of alert alarms

- BTAS.js
> add decoder name(AzureGraphAPI-json)  summary---(Successful Azure Login from malware-IP) handler

- BTAS.js
> login from malware-(ip,country) Adds an additional device_name description

- BTAS.js
…leted in short period of time)
> add description of the summary (Multiple Account Being Disabled or Deleted in short period of time)

- BTAS.js
> Fixed decoder name(m365-defender-json) partial ticket extraction content issue

- BTAS.js
> Set the Macau keyword detection time to one minute, and optimize the page automatic refresh

- BTAS.js
> Get the event alert link for MDE365 and Add a colored border to the flag of the notify

- BTAS.js
Add a feature:hides notifies when ticket page is swiped down and hides notifies when the mouse is over the notifyes
> Add a feature:hides notifies when ticket page is swiped down and hides notifies when the mouse is over the notifyes

- BTAS.js
> remove hides notifies feature and Moved the position of the Notice button

- BTAS.js
one assign me shortcut key, other one resolve ticket shortcut key
> add two shortcut key

- BTAS.js
Fixed MDE365AlertHandler description processCommandLine field powershell command and email content multiple line breaks
> Fixed MDE365AlertHandler description processCommandLine field powershell command and email content multiple line breaks

- BTAS.js
> add create dev ticket function three component options(default Wazuh,MDE,Cortex)

- BTAS.js
> add decoder name(Proofpoint_TAP) summary--(messagesDelivered event) more information

- BTAS.js
Fixed the issue(Multiple conditions matching semicolons have no effect) of matching Notify
> Fixed the issue(Multiple conditions matching semicolons have no effect) of matching Notify

- BTAS.js
cortex log日志信息是在Debug选项卡下的Raw Alert字段内
> fixed keyword matching in cortex log

- BTAS.js
Fixed the problem of missing content of ticket description in decode name(windows-syslog) part
> Fixed the problem of missing content of ticket description in decode name(windows-syslog) part

- BTAS.js
> modify decodername(m365-defender-json,mde-api-json) time(GMT+0) to time(GMT+8)

- BTAS.js
> "add decodername(m365-defender-json,mde-api-json) decode (powershell commandline)

- BTAS.js
分析师处理工单遇到的问题，当对工单完成评论后，工单会变成waiting for customer，但没有升级，这时分析师以为已处理完成或已升级，解决：BTAS实时监听work in progress按钮变为waiting for customer，且ORG内容是否为None
> add Standardize analyst processing manner

- BTAS.js
logsourcedomain:wkcda and summary:(Multiple failed user logon attempts to a service involving one user) need provide M365 Link
> logsourcedomain:wkcda and summary:(Multiple failed user logon attempts to a service involving one user) need provide M365 Link
